In [1]:
# If data is written from pandas library in Python, convert numeric data to numpy array by using numpy.array(data)
class LogisticRegression(object):
    import numpy as np
    def __init__(self, data, label, learningRate = 0.1, maxEpoch = 100, batchSize = 32):
        self.__data = data
        self.__label = label
        self.__learningRate = learningRate
        self.__maxEpoch = maxEpoch
        self.__batchSize = batchSize
        self.__weights = 0
        
    def __setWeights(self, weights):
        self.__weights = weights
    
    def __getWeights(self):
        return self.__weights
    
    # Activation function
    def __sigmoid(self,result):
        return 1 / (1 + np.exp(-result))
    
    def logisticRegFit(self):
        # initialize weights
        weights = np.random.randn(self.__data.shape[1]+1).reshape(-1,1)
        self.__data = np.insert(self.__data, 0, 1.0, axis=1)
        n_minibatches = len(self.__data) // self.__batchSize
        for epoch in range(self.__maxEpoch):
            # Mini Batch Gradient Descent
            for samples in range(n_minibatches + 1):
                dataMiniBatch = self.__data[samples * self.__batchSize:(samples + 1) * self.__batchSize,:]
                labelMiniBatch = self.__label[samples * self.__batchSize:(samples + 1) * self.__batchSize,:]
                if len(dataMiniBatch) == 0:
                    break
                predictions = np.dot(dataMiniBatch, weights).reshape(-1,1)
                predictions = self.__sigmoid(predictions)
                predictions = np.round(predictions)
                error = labelMiniBatch - predictions
                gradient = np.dot(dataMiniBatch.T, error)
                weights = weights + self.__learningRate*gradient
            #predictions = np.dot(self.__data, weights).reshape(-1,1)
            #error = self.__label - predictions
            #gradient = np.dot(self.__data.T, error)
            #weights = weights + self.__learningRate*gradient
        self.__setWeights(weights)
        return weights
    
    def scores(self):
        weights = self.__getWeights()
        predictions = np.dot(self.__data, weights).reshape(-1,1)
        predictions = self.__sigmoid(predictions)
        predictions = np.round(predictions)
        error = self.__label - predictions
        errorSquare = error**2
        mse = np.sum(errorSquare)
        mse = mse / len(self.__data)
        rmse = np.sqrt(mse)
        return {"MeanSquareError" : mse, "RootMeanSquareError" : rmse}
  
    def logisticRegPredict(self, data):
        weights = self.__getWeights()
        data = np.insert(data, 0, 1.0, axis=1)
        predictions = np.dot(data, weights).reshape(-1,1)
        predictions = self.__sigmoid(predictions)
        predictions = np.round(predictions)
        return predictions

In [2]:
import numpy as np
X = np.array([[0,0],[1,0],[0,1],[1,1]])
y = np.array([[0],[0],[0],[1]])
obj = LogisticRegression(X,y,0.5, 20)
X

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1]])

In [3]:
obj.logisticRegFit()

array([[-0.64079669],
       [ 0.5025185 ],
       [ 0.33920955]])

In [4]:
obj.scores()

{'MeanSquareError': 0.0, 'RootMeanSquareError': 0.0}

In [5]:
obj.logisticRegPredict(np.array([[0,0],[1,0],[0,1],[1,1]]))

array([[0.],
       [0.],
       [0.],
       [1.]])