In [1]:
# If data is written from pandas library in Python, convert numeric data to numpy array by using numpy.array(data)
class LogisticRegression(object):
    import numpy as np
    def __init__(self, data, label, learningRate = 0.1, maxEpoch = 100, batchSize = 32):
        self.__data = data
        self.__label = label
        self.__learningRate = learningRate
        self.__maxEpoch = maxEpoch
        self.__batchSize = batchSize
        self.__weights = 0
        
    def __setWeights(self, weights):
        self.__weights = weights
    
    def __getWeights(self):
        return self.__weights
    
    # Activation function
    def __sigmoid(self,result):
        return 1 / (1 + np.exp(-result))
    
    def logisticRegFit(self):
        # initialize weights
        weights = np.random.randn(self.__data.shape[1]+1).reshape(-1,1)
        self.__data = np.insert(self.__data, 0, 1.0, axis=1)
        n_minibatches = len(self.__data) // self.__batchSize
        for epoch in range(self.__maxEpoch):
            # Mini Batch Gradient Descent
            for samples in range(n_minibatches + 1):
                dataMiniBatch = self.__data[samples * self.__batchSize:(samples + 1) * self.__batchSize,:]
                labelMiniBatch = self.__label[samples * self.__batchSize:(samples + 1) * self.__batchSize,:]
                if len(dataMiniBatch) == 0:
                    break
                predictions = np.dot(dataMiniBatch, weights).reshape(-1,1)
                predictions = self.__sigmoid(predictions)
                predictions = np.round(predictions)
                error = labelMiniBatch - predictions
                gradient = np.dot(dataMiniBatch.T, error)
                weights = weights + self.__learningRate*gradient
            #predictions = np.dot(self.__data, weights).reshape(-1,1)
            #error = self.__label - predictions
            #gradient = np.dot(self.__data.T, error)
            #weights = weights + self.__learningRate*gradient
        self.__setWeights(weights)
        return weights
    
    def scores(self):
        weights = self.__getWeights()
        predictions = np.dot(self.__data, weights).reshape(-1,1)
        predictions = self.__sigmoid(predictions)
        predictions = np.round(predictions)
        error = self.__label - predictions
        errorSquare = error**2
        mse = np.sum(errorSquare)
        mse = mse / len(self.__data)
        rmse = np.sqrt(mse)
        return {"MeanSquareError" : mse, "RootMeanSquareError" : rmse, "Accuracy":(predictions == self.__label).mean()}
  
    def logisticRegPredict(self, data):
        weights = self.__getWeights()
        data = np.insert(data, 0, 1.0, axis=1)
        predictions = np.dot(data, weights).reshape(-1,1)
        predictions = self.__sigmoid(predictions)
        predictions = np.round(predictions)
        return predictions

In [2]:
import numpy as np
X = np.array([[0,0],[1,0],[0,1],[1,1]])
y = np.array([[0],[0],[0],[1]])
obj = LogisticRegression(X,y,0.5, 20)
X

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1]])

In [3]:
obj.logisticRegFit()

array([[-0.99253063],
       [ 0.49866269],
       [ 0.89851897]])

In [4]:
obj.scores()

{'MeanSquareError': 0.0, 'RootMeanSquareError': 0.0, 'Accuracy': 1.0}

In [5]:
obj.logisticRegPredict(np.array([[0,0],[1,0],[0,1],[1,1]]))

array([[0.],
       [0.],
       [0.],
       [1.]])

## Logistic Regression with Multiple Class

In [6]:
from sklearn.datasets import load_iris
iris = load_iris()
import numpy as np
X = iris.data
y = iris.target
y = y.reshape(-1,1)
np.unique(y)

array([0, 1, 2])

In [7]:
y1 = np.where(y == 0, 1, 0)
y2 = np.where(y == 1, 1, 0)
y3 = np.where(y == 2, 1, 0)

In [8]:
obj = LogisticRegression(X,y1,0.1, 2000)

In [9]:
obj.logisticRegFit()

array([[  1.70635533],
       [  3.66281038],
       [ 10.77766634],
       [-15.3886199 ],
       [ -6.79471519]])

In [10]:
obj.scores()

{'MeanSquareError': 0.0, 'RootMeanSquareError': 0.0, 'Accuracy': 1.0}

In [11]:
pred1 = obj.logisticRegPredict(X)

In [19]:
obj = LogisticRegression(X,y2,0.00001, 2000)
obj.logisticRegFit()
obj.scores()

{'MeanSquareError': 0.24,
 'RootMeanSquareError': 0.4898979485566356,
 'Accuracy': 0.76}

In [20]:
pred2 = obj.logisticRegPredict(X)

In [21]:
obj = LogisticRegression(X,y3,0.1, 2000)
obj.logisticRegFit()
obj.scores()

{'MeanSquareError': 0.02666666666666667,
 'RootMeanSquareError': 0.16329931618554522,
 'Accuracy': 0.9733333333333334}

In [22]:
pred3 = obj.logisticRegPredict(X)

In [23]:
pred = np.zeros(len(pred1))
for i in range(len(pred)):
    if pred2[i] == 1:
        pred[i] = 1
    if pred3[i] == 1:
        pred[i] = 2
    if pred1[i] == 1:
        pred[i] = 0
pred = pred.reshape(-1,1)
pred

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [2.],
       [1.],
       [2.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [1.],

In [24]:
(pred == y).mean()

0.86